### ISSUE TITLE
Create the endpoint to back-up a wallet by downloading the account file (yaml) in clear (decrypted)

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra-plugin-wallet#108]

**Comment by Thykof** [comment]
the file is here: https://github.com/massalabs/thyra-plugin-wallet/blob/main/api/walletApi-V0.yml

I suggest you to use https://editor.swagger.io for better preview

**Comment by SlnPons** [comment]
I can see the endpoint but it's not clear to me how it will work. If possible, could you explain it to me please? What's the process exactly? 
Based on the button that the user presses it triggers the same endpoint but with different characteristics?

**Comment by SlnPons** [comment]
Yep, I know it's only on the back-end side. All good with that, juste trying to understand the process in place to see if we could use it else where (not just on wallet but other ideas Ive got :) )
