### ISSUE TITLE
Improve web-frontend integration to server

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra-plugin-wallet#125]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

following #110 some small tasks need to be done.

**How to**
*List the step-by-step to get it do if needed - PM*

- [x] https://github.com/massalabs/thyra-plugin-wallet/pull/110#discussion_r1183671197
- [x] remove story book? https://github.com/massalabs/thyra-plugin-wallet/pull/110#discussion_r1176156448
- [x] improve react router utilization
- [x] make it work in no-standalone mode (with MassaStation)

Still todo:
- [x] fix 404 page

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
@mazmassa should I remove the storybook from the wallet frontend application?

**Comment by mazmassa** [comment]
> @mazmassa should I remove the storybook from the wallet frontend application?

I would say yes! What's the pourpose to have it there!? 🤔

**Comment by SlnPons** [comment]
@Thykof can you confirm that I can really test this? Can we assume that if the 1st screen of the wallet is well done, this ticket is done too?

**Comment by Thykof** [comment]
@SlnPons 

> can you confirm that I can really test this

if you really want to test you can follow the process in QA review section of this PR https://github.com/massalabs/thyra-plugin-wallet/pull/110#issue-1678498862 but it's very technical and ugly ^^

> Can we assume that if the 1st screen of the wallet is well done, this ticket is done too?

absolutely
