### ISSUE TITLE
add select account

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/thyra-plugin-wallet#131]
**Context**
This will contribute to the integration of the wallet frontend interface. It corresponds to the wallet [screen](https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=71-1810&t=u0UZFM30uctqX0gx-4) two where the user selects an account. 

![Screenshot from 2023-05-09 10-23-13](https://user-images.githubusercontent.com/90157528/237038358-bdee1d36-83d4-413f-8593-adf3fe938dcd.png)

**User flow**
The user has two options : 
- Clicks on an existing account which redirects him to the wallet home page
- User creates an account

**How to**

- [ ] Create page component
- [ ] Implement ui-kit components
- [ ] send to review

**Technical details**
This should be straight forward and not reserve any bad surprises

**Comment by SlnPons** [comment]
Nice Job @pivilartisant !! :)
