### ISSUE TITLE
Delete code related to Thyra wallet

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#14]
**Context**
Thyra wallet has been isolated as it is so we can use it as a plug-in. Now it is isolated and connected to thyra via API we need to clean it and later on to improve it adding new features. 
The objective of this ticket is to delete code related to Thyra wallet now it's working as a plug-in. 

**User flow**
* As an Inno team dev, I want to work on a clean code where everything is used and useful otherwise I can get rid of it. 

**Technical details** 
To be be added by the dev prior to start the work.

**Comment by SlnPons** [comment]
@B-Naoufal if you already know some of the function / code that needs to be removed can you add them in to the tech details part of the description please? 
Cheers

**Comment by 0xMazout** [comment]
In blocked until some clarifications are made about the perimeter and the limits of the links to web on chain and wallet on thyra

**Comment by SlnPons** [comment]
@B-Naoufal @0xMazout after discussing this issue w/ you Naoufal, Pierre as a plugin referee and Greg, we agreed that the code cleaning of the wallet plugin has been done with this ticket: 
https://github.com/massalabs/thyra-plugin-wallet/issues/21

So this one is more relevant for Thyra wallet side. Which means that I'll close this ticket and create another one in appropriate repo. 
On top of that, please note that the code cleaning of the wallet on Thyra side will be done AFTER the wallet plugin is fully functional, iso to thrya wallet AND correctly connected to other plugins and web-on. IE: not a priority for now.
