### ISSUE TITLE
Connect the "import and create account" front-end to the back-end

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#162]
Screen & designs: 
https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=324-5834&t=BiB0WsXGAUd7OpUX-0

<img width="628" alt="image" src="https://github.com/massalabs/thyra-plugin-wallet/assets/109611779/92032c00-d468-4f52-af30-4eb25e869fbb">

- Page URL: my.massa/massastation/massalabs/wallet/connection

Implementation details: 

- [ ] Connect the "create an account" button to "create an account" page
* URL of the "create an account" page: my.massa/massastation/massalabs/wallet/create/1
- [ ] Connect the "import an account" button to the "import" path using wails

**Comment by SlnPons** [comment]
@maxime-carabina For the "create an account". It's ok, I solved my problem (the branch I was using wasn't up to date...) 

Other comments are still to be done.

**Comment by maxime-carabina** [comment]
> @maxime-carabina this page is KO.
> 
> For the "create an account",
> 
> * the button is not connected to the creation step-by-step screens. So not usable. Let's do this asap.
> 
> For the "Import an existing account",
> 
> * with a .yaml file: it doesn't work. No matter which file you import, you always have the same error message "The file format must be .yaml".
>   --> this is not correct. Error messages should be different if the file info aren't correct vs. is the file format is not good. It is super confusing for the end-user to upload a .yaml and see this error.
>   cc @Thykof probably you can help ;)
> * with a private key:
> 
> 1. Enter a private key: very niceeeeee!!! :) :)
> 2. Define a username: ✅ 
> 3. Define a password: ✅
