### ISSUE TITLE
refactor the tests

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/thyra-plugin-wallet#174]
**Context**
refactoring the wallet test with the assert package
**User flow**

**How to**
use the assert packages for the following tests
- [x] #191
- [x] #175
- [x] #181
- [x] #185
- [x] #188
- [x] #190

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
run task test to test it

**Comment by SlnPons** [comment]
@Pierregvx I think I'll need your help to test this ticket 😅
The explanations aren't clear enough to me.
