### ISSUE TITLE
Create import an existing wallet function

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#18]
**Context** 
Users need to be able to import on Thyra existing one or many existing wallets in order to keep their MAS but also to avoid make things more complicated for them. 
The most important points are: 
* Thyra wallet and important wallet (from massa-client) MUST have the same format as input and output.
* All wallets need to use the same crypto algorithm. The one used by the core team, see here: https://github.com/massalabs/private-deployment/blob/main/testnet/cipher.py
* All wallet need to be stored in the same files user the plugins/thyra-plugin-wallet

**User flow**
1. User starts Thyra 
2. User accesses the Wallet Plug-in page typing: my.massa/thyra/massa-labs/wallet
3. User sees the "import a wallet" button
4. User clicks on the "import a wallet" button and a Thyra pop-up opens on his machine
5. User sees a pop-up from his machine asking for:
* Wallet name: text field
* Password: text field
* Private key: text field
* Cancel / Import buttons
* --> if user clicks on "Cancel", error message "Action stopped. No wallet added to Thyra" is displayed
6. User clicks on "Import" button and sees his/her wallet added to the list of wallet on Wallet plug-in page

**How to**

- [ ] Make sure wallets generated by the plug-in are exactly the same as the wallets generated by massa-client (ie: same format, same crypto-algo, all stored at the same place). Massa-client wallets might be killed so this plug-in must be able to use and provide **exactly** the same services as the ones developped by the Core team. Please contact me to deep dive in the details before starting this ticket. 
- [ ] Change the URL of the plugin wallet to match the one described above
- [ ] Rename the "Load a wallet" button on the wallet plug-in page in "Import a wallet"
- [ ] Rename "Load" button to "Import" in the pop-up
- [ ] Update the "Cancel" error message AND add it to the error library

**Technical details**
To be added by the dev prior to star the task

**Comment by SebastienValla** [comment]
massa-client and thyra have the same wallet encryption, only difference is the file format, we use json, they use.dat.
They decode their wallet this way : 
first 4 bytes -> version
next 12 bytes -> salt
next 12 bytes -> nonce
they the wallet datas.
You can find what they use here : 
https://github.com/massalabs/massa/blob/main/massa-cipher/src/decrypt.rs
