### ISSUE TITLE
Wallet import- change the error message when wrong password entered

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#19]
**User flow**

As a user, when I load an existing wallet to thyra and that I entered the wrong password, I want to see an error message that allows me to know that my password is

**How to**

 Change current error message "Error while creating your wallet. Try again" to "Wrong password. Try again"

**Comment by Thykof** [comment]
The confirm dialog on delete account is missing, the associated PR adds it and display proper message on cancel
