### ISSUE TITLE
Connect the account creation step 1 front-end to the back-end

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra-plugin-wallet#211]
*This issue is part of #81*

Account creation step one it the one that prompt the nickname.

> Rules to implement:
> Name can’t contain special characters
> -> on the click, do the check & display error message: “Special characters can’t be used”  /!\ I think that the fact that we can’t use special character is due to a bug that can be solved. If we have time, it would be better to solve the bug and remove this rule.
> Same name can’t be used twice. Prevent user from creating an account with twice the same name.
> -> on the click, do the check and display error message: “This account name already exists” 

How to:
- [x] #214 
- [x] show error message: #223
- [ ] nickname unique constraint: #231 
- [x] #234

**Comment by SlnPons** [comment]
Could you link to this issue the ticket you're working on @Thykof to connect this page to the error logic please? 
I'm afraid we'll forget this. And officially this screen isn't done yet.

**Comment by Thykof** [comment]
I was working on https://github.com/massalabs/thyra-plugin-wallet/pull/223 there is no issue specifically about connecting the errors yet
