### ISSUE TITLE
Wallet's balance not getting updated on wallet plug-in

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#22]
**Describe the bug**
The wallet balance is not getting updated after the wallet's address has been shared on Massa faucet channel

**To Reproduce**

1. Create a wallet with wallet plug-in
2. Send your address to the faucet 
3. See the balance that is NOT updated

**Expected behavior**
The balance should be updated to reflect the tokens you have on your wallet.

**Screenshots**
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/109611779/210251956-43a5a338-61a7-4802-928b-6b6e8e20f6fe.png">

<img width="969" alt="image" src="https://user-images.githubusercontent.com/109611779/210251983-72b4c6b2-2491-45b1-839f-0f37172bdc6b.png">

**Thyra version**
Ltest on the main branch on 02/01/2023 at 3pm

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Comment by SlnPons** [comment]
After checking it on TestNet 18, I can still experience this bug on my side. 
I follow the same procedure as described above with a new wallet created just now.
Could you have a look please?

**Comment by SebastienValla** [comment]
blocked by https://github.com/massalabs/thyra/issues/388
