### ISSUE TITLE
Update "back up" front-end screen

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/thyra-plugin-wallet#220]
![image](https://github.com/massalabs/thyra-plugin-wallet/assets/72019005/5ab0e3fb-d691-4f09-8e91-c9fc028b14ac)

**Comment by SlnPons** [comment]
@Thykof back up works well. Well done guys :) :) 
Could we change the success message to "Your .yaml file has been downloaded" please? 
Only if it takes less than 5 min

**Comment by Thykof** [comment]
yes it's done in https://github.com/massalabs/thyra-plugin-wallet/pull/290
