### ISSUE TITLE
Test Drag N Drop import 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/thyra-plugin-wallet#230]
**Context**
The figma design has a drag and drop that we need to test because the component was developed after the wails screen 

![Screenshot from 2023-05-19 16-25-08](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/5980da44-854c-439a-9a2e-111f291b69c2)

**User flow**
The user drags a .yml file once the file is uploaded the username appears 
![Screenshot from 2023-05-19 16-27-34](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/6d3ad292-0882-40ce-86b7-d48bce0be581)

**Comment by SlnPons** [comment]
@pivilartisant I don't think we have implemented this? Have we? 
Can you deprecate this issue with a comment if not and close it please ;)

**Comment by pivilartisant** [comment]
We have implemented this ! It's in the wails and in the search side panel ! But this issue is outdated so I will close it :)
