### ISSUE TITLE
Passwords are displayed at each operation

### ISSUE THREAD

**Issue by Elli610** [massalabs/thyra-plugin-wallet#276]
**Describe the bug**
Each time I have to enter my password to confirm an operation, it is displayed for about 1 second when I press the enter key to validate.

**To Reproduce**
Each time I have to enter my password to confirm an operation, it is displayed for about 1 second when I press the enter key to validate. launch an operation, type your password and press enter

**Expected behavior**
Passwords allow access to the entire wallet. You can't keep them secret if they show up every time you enter them. They should be prevented from being displayed. even if it's only for a second

**Thyra version**
I built The thyra-wallet from this commit: https://github.com/massalabs/thyra-plugin-wallet/commit/625f017947aa14c306a3206b02ad0b383724474c

**Desktop (please complete the following information):**
 - OS: Windows 11 (22H2)
 - Browser: brave

**Comment by SlnPons** [comment]
Closing this issue as it's not relevant with new wallet. 
But @Elli610 I'll ask you to test the new one to confirm this ;)
