### ISSUE TITLE
Have a wallet encoding iso with massa-client

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra-plugin-wallet#29]
Context
Users need to be able to import on Thyra existing one or many existing wallets in order to keep their MAS but also to avoid make things more complicated for them.
The most important points are:

    Thyra wallet and important wallet (from massa-client) MUST have the same format as input and output.
    All wallets need to use the same crypto algorithm. The one used by the core team, see here: https://github.com/massalabs/private-deployment/blob/main/testnet/cipher.py
    All wallet need to be stored in the same files user the plugins/thyra-plugin-wallet

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
This task is to implement this standard: https://github.com/massalabs/massa-standards/blob/main/wallet/file-format.md

**Comment by Thykof** [comment]
for QA review you can create a new yaml and see in the config folder that the file in store in yaml format, open it and see you nickname, address...

**Comment by Thykof** [comment]
QA review fail:

reading the wallet standard, it seems that the .yml should use table so we don't have new line at each byte.  It will be more readable, let's try to do it! :)

**Comment by SlnPons** [comment]
@Thykof thanks a lot, I agree it's better to follow the standard very specifically. 
After thinking a bit more about it, it is important that the .yml are stored on the wallet plugin file and not on thyra. This will be way (way) better to scale. 

I'll create another issue to handle this point as this ticket is more than done for now.
