### ISSUE TITLE
User can switch theme

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra-plugin-wallet#307]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

User can click on this menu item to switch theme:
![image](https://github.com/massalabs/thyra-plugin-wallet/assets/11590067/efa5292e-1fe6-4ead-993c-3c554d2c8710)

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by Thykof** [comment]
@SlnPons maybe it's not in milestone Wallet#2?

**Comment by SlnPons** [comment]
It's it "super easy" to do this thanks to the UI kits and all composants that are already set in both themes? 
I was under the impression that it was one of the strength of such a ui-kit. 
cc @mazmassa maybe I misunderstood. Let me know if it's not trivial.

**Comment by Thykof** [comment]
You are tight, all components exists in both themes. We just need to create the system to switch from one theme to another. I think it's "quite easy"

**Comment by mazmassa** [comment]
> We just need to create the system to switch from one theme to another. I think it's "quite easy"

Indeed! All was done to support the switch between themes. However, we must give the users the way to do. That's what @Thykof is mentioning. This will happen when clicking on the menu option... and this was not done yet.

BTW, @Thykof we have a good example done by Lilyan (http://localhost:6006/?path=/story/components-theme-mode--theme-mode). The way we setup in the localStorage and etc...

Let me know if you need help to do that.

**Comment by Thykof** [comment]
less than a day

**Comment by SlnPons** [comment]
Ok thanks a lot to both of you! It's defo a nice-to-have then. Not a priority for now, I would say: 
1. send coins 
2. settings
3. receive coins
4. teaser screens (for non-available features)
5. switch mode light / dark

**Comment by SlnPons** [comment]
Done
