### ISSUE TITLE
api not working on the "function rest wallet list"

### ISSUE THREAD

**Issue by noesusset** [massalabs/thyra-plugin-wallet#31]
**Describe the bug**

The "rest wallet list" api calls doesnt return the informations about the KeyPair such as "nonce", "privateKey"...

**To Reproduce**

after installing the thyra-plugin-wallet repo run
```
go run cmd/massa-wallet/main.go
```

then we can create a wallet 
and using for example postman we can call the api and see that there is some missing information

![image](https://user-images.githubusercontent.com/96011618/217648854-d39ba9bf-4d68-41ac-908e-60d482f1a1a9.png)

**Expected behavior**

we should be able to see the information about the KeyPair

**Comment by SlnPons** [comment]
@Thykof @gregLibert is it fair to say that this issue will be solved / a proper solution will be defined with the wallet standard? 

If not, what can we do so solve this issue on the wallet plugin please?

**Comment by gregLibert** [comment]
> @Thykof @gregLibert is it fair to say that this issue will be solved / a proper solution will be defined with the wallet standard?

Nope

> If not, what can we do so solve this issue on the wallet plugin please?

This issue shouldn't be solved. the wallet plugin shouldn't extract key pair. if the caller need to sign something, the Sign endpoint should be used instead.
