### ISSUE TITLE
SignOperation change b64 encoding

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/thyra-plugin-wallet#40]
**Context**
*Describe / explain why we should do this: motivations, context or other info. Keep it brief and simple - PM*

**User flow**
*Describe the user flow using user stories so the end result is super clear - PM*

**How to**
*List the step-by-step to get it do if needed - PM*

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by SlnPons** [comment]
@ASAPSegfault how can I test this?

**Comment by B-Naoufal** [comment]
We have a unit test for signOperation !

**Comment by SlnPons** [comment]
On the plugin wallet @B-Naoufal ? 🥳
Can you send me the link to where it is in the code please? Will be helpful for when I'll the run team about unit test on endpoints
