### ISSUE TITLE
Connect plug wallet plugin to new plugin manager

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#42]
**Context**
This issue is part of the 1st milestone to achieve for the Thyra squad working on the wallet plugin. See [here](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4#b67bc640e5414b328b64fe475658f428) for all details.

The objective of this issue is to connect the wallet plugin to the "new plugin manager" so that this plugin is working properly.

**User flow**
N/A this issue will concern the back-end only

**How to**

- [x] Remove existing connections to the old plugin manager
- [x] Connect all wallet plugin functionalities to new plugin manager

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Using postman? - please guys help me to define how I will be able to test that it's working well :)

**Comment by Thykof** [comment]
blocked by https://github.com/massalabs/thyra-plugin-hello-world/pull/8

**Comment by SlnPons** [comment]
@Thykof I'm blocked to test this issue :/ 
Here is what I'm doing: 
1. I tried to install the plugin using the front-end and un URL of the zip from the release: my.massa/thyra/plugin-manager/ 
--> Got a 500 error. I do believe that it's due to the fact that the expected format is URL of a zip and here it's binary. 
Actions:
* I created an issue so we can use the front-end to install all Massa plugin easily... feel free to edit it. https://github.com/massalabs/thyra/issues/544 


2. I tried to follow the readme for developers. 
I followed each step one by one but I still can't see the plugin appearing on the front-end list to access it "simply". 


![Image](https://user-images.githubusercontent.com/109611779/225629253-af31f9c3-41b0-4fd5-9c2c-402383a69ee8.png)



I'm probably doing sth wrong. Could you help or tell me who could help if you have too much on your plate please?

**Comment by Thykof** [comment]
@SlnPons about your second point, please run `./build.sh` before `./manual-install.sh`
