### ISSUE TITLE
No favicon for the wallet

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra-plugin-wallet#429]
I don't see any favicon on my browser tab:
![image](https://github.com/massalabs/thyra-plugin-wallet/assets/16623956/ac30356b-0519-47bc-84ba-f972e629104b)
For instance, I have the following for thyra:
![image](https://github.com/massalabs/thyra-plugin-wallet/assets/16623956/e8984b49-d487-4fc1-9e31-7bf5dd548b40)

**Comment by Thykof** [comment]
duplicate of https://github.com/massalabs/thyra-plugin-wallet/issues/422
