### ISSUE TITLE
CORS: cross-origin request to solve on the long-term

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#53]
**Describe the bug**
When trying to use the plugin wallet, i've got an error message telling me explaining that the request has been blocked. 

**To Reproduce**

1. Install the plugin wallet (using the Readme: developer part) 
2. Access the port mention on your terminal 
3. try to create a wallet 
4. See errors in screenshot

**Expected behavior**
You can use the plugin wallets and all plugins (in case this issue is not only related to the wallet plugin please try to solve it)
All plugins should work

**Screenshots**
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/109611779/225630912-c8c3b19f-7cfc-4148-843a-3f1db2850e27.png">

**Thyra version**
V0.1.12

**Additional context**
If this issue is not related to the wallet plugin but to thyra, please move this issue with the same priority and ping me ;)

**Comment by Thykof** [comment]
probably duplicate of https://github.com/massalabs/thyra-plugin-wallet/issues/46

let's test again when #48  is merged.

**Comment by SlnPons** [comment]
https://github.com/massalabs/thyra-plugin-wallet/issues/46
