### ISSUE TITLE
implement RestWalletGet

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra-plugin-wallet#59]

**Comment by Thykof** [comment]
blocked: I need to rebase to fix conflicts but waiting for main branch build to be fixed, see #65

**Comment by SlnPons** [comment]
@Thykof how can I test this ticket please?

**Comment by Thykof** [comment]
# QA:

## Option 1
- run `STANDALONE=1 go run cmd/massa-wallet/thyra-plugin-wallet.go`
- create an account with API: 
```
curl --location 'http://127.0.0.1:8080/rest/wallet' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{
  "nickname": "created",
  "password": "1234"
}'
```
- get the account with API:
```
curl --location 'http://127.0.0.1:8080/rest/wallet' \
--header 'Accept: application/json'
```

## Option 2
You can also use the postman collection

## Option 3
Install the wallet manually and see that everything work, especially web-on-chain page (because this page use the implemented endpoint RestWalletGet)
