### ISSUE TITLE
Uniform Serving Massa Wallet Link/PORT

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/thyra-plugin-wallet#6]
**Describe the bug**
Serving Massa Wallet is done on a random Port not the one mentioned on README http://127.0.0.1:33049 
![image](https://user-images.githubusercontent.com/16125633/207040947-5091a370-d9fd-4ccb-9ca0-4597d52c6684.png)
To access to he wallet : http://127.0.0.1:[RANDOM-PORT]/web/wallet.html#

**Comment by SlnPons** [comment]
@B-Naoufal @peterjah should we have a discussion about how to define the port that a specific plug-in (here the wallet) will use? 
I'm not 100% on how this will be defined... keen to understand this point better :)

**Comment by B-Naoufal** [comment]
@SlnPons this issue is resolved  with this PR https://github.com/massalabs/thyra-plugin-wallet/pull/12/files, so i will close it
