### ISSUE TITLE
Update the wallet import feature 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#82]
**Prerequisite**
#81 
#80 

**Context**
Part of mainnet plan - [Wallet product milestone 2](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4)

--> the objective of this ticket is to implement the import functionality as expected for the mainnet.

**User flow**
As a user, I want to be able to import existing Massa wallets on the wallet plugin so that I can use it easily by either 
1. uploading a yml file
2. OR by adding my private key + nickname + password

Wails Design: https://www.figma.com/proto/LSaOibVDFb1reF6FePVn5l/Massastation?node-id=562-9565&scaling=min-zoom&page-id=324%3A5834&starting-point-node-id=562%3A9449

MassaWallet designs: https://www.figma.com/proto/LSaOibVDFb1reF6FePVn5l/Massastation?node-id=562-9449&scaling=min-zoom&page-id=324%3A5834&starting-point-node-id=562%3A9449

**How to**

- [ ] add endpoint to import an account by yaml file (to be confirmed)
- [ ] add endpoint to import an account by private key + nickname + password
- [ ] Implement option 1 described above
- [ ] rework Fyne into Wails to implement option 2 above
- [ ] Create associate front-end for users to perform these actions easily
- [ ] Do a release so it can be tested

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

User click on "Import an existing account", Wails GUI opens and ask for option 1 and 2.

Option#1
- ask to select a file on your computer filesystem

Option#2
- form that ask for nickname, private key and new password (and password confirmation)

**QA testing**
Test is from a user perspective

**Comment by Thykof** [comment]
>  Do a release so it can be tested

You will be able to test it without a release
